server:
  port: 5555
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka8080.com:8080/eureka/
  instance:
    instance-id: zuul
    prefer-ip-address: true


#info:
#  app.name: atguigu-microcloud
#  company.name: yourcompanyname
#  build.artifactId: $project.artifactId$
#  build.version: $project.version$
zuul:
  routes:
    h.serviceId: clould-provider
    h.path: /mydept/**
  prefix: /mist
  ignored-services: "*"      #忽略服务名称
