server:
   port: 7002
eureka:
# server:
#    enable-self-preservation: true #关闭其自我保护（开发环境可以操作，方便）
 server:
    enable-self-preservation: false #是否开启自我保护模式
    eviction-interval-timer-in-ms: 60000 #服务注册表清理间隔(单位:毫秒,默认是60*1000)
 instance:
    hostname:  eureka7002.com  #eureka服务端的实例名称
 client:
    # 单机状态地址是自己所以需要关闭自己注册自己，集群时应放开
    #     register-with-eureka: false #服务注册,是否将自己注册到Eureka服务中
    #     fetch-registry: false #服务发现,是否从Eureka中获取注册信息
     serviceUrl: #Eureka客户端与Eureka服务端的交互地址,高可用状态配对方的地址,单机状态配自己的地址(如果不配置,默认本机8761端口)
         defaultZone: http://eureka8080.com:8080/eureka/,http://eureka7003.com:7003/eureka/
        # defaultZone: http://localhost:8771/eureka/