                      server:
                          port: 9005

                      eureka:
                        client:
                          serviceUrl:
                            defaultZone: http://eureka8080.com:8080/eureka/
                      spring:
                        profiles:
                          active: native

                        application:
                          name: springcloud-config-server


                      #  cloud:
                      #    config:
                      #      server:
                      #        git:
                      #          uri:
                      #          search-paths:
                      #          username:
                      #          password: